I'm sorry, but an uncaught exception occurred.

While running game code:
  File "game/scripts/days/dayTransition.rpy", line 5, in script
    with Fade(2.0, 2.0)
TypeError: Fade() missing 1 required positional argument: 'in_time'

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "game/scripts/days/dayTransition.rpy", line 5, in script
    with Fade(2.0, 2.0)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\ast.py", line 1638, in execute
    renpy.exports.with_statement(trans, paired=paired)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\exports.py", line 1653, in with_statement
    return renpy.game.interface.do_with(trans, paired, clear=clear)
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\display\core.py", line 2797, in do_with
    return self.interact(trans_pause=True,
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\display\core.py", line 3376, in interact
    repeat, rv = self.interact_core(preloads=preloads, trans_pause=trans_pause, pause=pause, pause_start=pause_start, **kwargs) # type: ignore
  File "C:\Users\alext\OneDrive - Universidade de Lisboa\Documentos\Programas\renpy-8.0.0-sdk\renpy\display\core.py", line 3740, in interact_core
    trans = self.ongoing_transition[None](
TypeError: Fade() missing 1 required positional argument: 'in_time'

Windows-10-10.0.19044 AMD64
Ren'Py 8.0.0.22062402
Treebulations 
Sun Nov  6 14:32:07 2022
